import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { 
  Store, 
  MapPin, 
  ArrowRight, 
  Sparkles, 
  CheckCircle2, 
  MessageCircle,
  Loader2
} from 'lucide-react';
import { useFirebase } from '../components/FirebaseProvider';
import { db } from '../lib/firebase';
import { doc, setDoc, updateDoc } from 'firebase/firestore';
import { Seller } from '../types';

const TradePresets = [
  { label: 'Veggie Vendor', icon: '🥬', category: 'agri', subcategory: 'Vegetables', desc: 'Fresh local farm vegetables sorted daily direct from Eswatini soil.' },
  { label: 'Fruit Seller', icon: '🍎', category: 'agri', subcategory: 'Fruits', desc: 'Ripe, delicious tropical and citrus fruits.' },
  { label: 'Street Food Stall', icon: '🍲', category: 'food', subcategory: 'Street food', desc: 'Warm, savory home-made local meals, braai & snacks.' },
  { label: 'Tailor/Fashion', icon: '🧵', category: 'clothing', subcategory: 'Tailoring', desc: 'Custom traditional fits and professional stitching.' },
  { label: 'Hair Salon', icon: '💇', category: 'beauty', subcategory: 'Hair salons', desc: 'Modern styles, cuts, and braiding.' },
  { label: 'Mechanic Workshops', icon: '🔧', category: 'automotive', subcategory: 'Mechanics', desc: 'Reliable car diagnostics, repairs, and tuning.' },
  { label: 'Plumbing Service', icon: '🚰', category: 'construction', subcategory: 'Plumbers', desc: 'Expert leak repairs, installations, and piping.' },
  { label: 'Phone Repairs', icon: '📱', category: 'electronics', subcategory: 'Phones', desc: 'Screen repairs, battery replacement, and accessories.' }
];

export default function RegisterSeller() {
  const navigate = useNavigate();
  const { categories, user, refreshProfile } = useFirebase();

  // Onboarding Form States
  const [shopName, setShopName] = useState('');
  const [category, setCategory] = useState('agri');
  const [subcategory, setSubcategory] = useState('Vegetables');
  const [whatsapp, setWhatsapp] = useState('');
  const [location, setLocation] = useState('');
  const [desc, setDesc] = useState('');
  const [logoPreset, setLogoPreset] = useState('🟢');
  const [isSubmitting, setIsSubmitting] = useState(false);

  // Apply template immediately
  const handleApplyPreset = (preset: typeof TradePresets[0]) => {
    setCategory(preset.category);
    setSubcategory(preset.subcategory);
    setDesc(preset.desc);
    setLogoPreset(preset.icon);
    if (!shopName) {
      setShopName(`My ${preset.label} Stall`);
    }
  };

  const handleAutoGenerateDesc = () => {
    const selectedCatObj = categories.find(c => c.id === category);
    const categoryLabel = selectedCatObj ? selectedCatObj.name : 'Local Goods';
    const possibleName = shopName || 'Our humble stall';
    
    const generatorTemplates = [
      `Welcome to ${possibleName}! We are proud local traders specializing in high-quality ${subcategory} and family-friendly products in Eswatini. Chat with us directly on WhatsApp to check today's stock and arrange fast collection or delivery!`,
      `Quality and freshness at ${possibleName}. Offering premium ${subcategory} in ${location || 'Mbabane'}. Reach out directly on WhatsApp to place your order now!`,
      `Your neighborhood stall for fresh ${subcategory}. At ${possibleName}, we provide friendly service and affordable prices. Message us on WhatsApp for daily specials!`
    ];
    
    const randomIdx = Math.floor(Math.random() * generatorTemplates.length);
    setDesc(generatorTemplates[randomIdx]);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!shopName || !whatsapp || !location) {
      alert('Please fill in your shop name, WhatsApp number, and location.');
      return;
    }

    setIsSubmitting(true);
    try {
      const newSellerId = `seller-${Date.now().toString(36)}`;
      const cleanPhone = whatsapp.startsWith('+') ? whatsapp : `+268 ${whatsapp.replace(/[^\d]/g, '')}`;

      const newSellerObj: Seller = {
        id: newSellerId,
        userId: user?.uid || undefined,
        name: shopName,
        location: location || 'Mbabane Central Market, Stall 4',
        hours: '08:00 - 17:30',
        phone: cleanPhone,
        whatsapp: cleanPhone,
        rating: 5.0,
        reviews: 0,
        deliveryAvailable: true,
        pickupAvailable: true,
        paymentMethods: ['MTN MoMo', 'Cash on Delivery', 'Pay on Collection', 'Debit Card'],
        bannerUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&q=80&w=800',
        logoUrl: 'https://images.unsplash.com/photo-1596422846543-74c6fc0e2811?auto=format&fit=crop&q=80&w=200',
        description: desc || 'Quality local products and services in Eswatini.',
        verificationLevel: 'basic',
        category: categories.find(c => c.id === category)?.name || 'Agriculture',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
      };

      // 1. Save seller to Firestore
      await setDoc(doc(db, 'sellers', newSellerId), newSellerObj);

      // 2. Update user profile with seller role
      if (user) {
        await updateDoc(doc(db, 'users', user.uid), {
          role: 'SELLER',
          sellerId: newSellerId,
          updatedAt: new Date().toISOString()
        });
        await refreshProfile();
      }

      localStorage.setItem('emakethe_active_seller_id', newSellerId);
      navigate('/dashboard');
    } catch (err: any) {
      console.error('Error registering seller:', err);
      alert('Failed to register seller profile: ' + err.message);
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="bg-slate-50 min-h-screen pb-24 w-full flex flex-col font-sans">
      {/* Header Banner */}
      <div className="bg-emerald-700 px-6 pt-10 pb-12 rounded-b-[40px] text-white shadow-lg relative overflow-hidden">
        <div className="max-w-md mx-auto">
          <span className="text-[10px] bg-emerald-500/30 text-emerald-100 font-extrabold px-3 py-1 rounded-full uppercase tracking-wider border border-white/10">
            ⏰ 2-Minute Setup
          </span>
          <h1 className="text-2xl font-black mt-2 font-display tracking-tight text-white leading-tight">
            Register Your Trader Stall
          </h1>
          <p className="text-emerald-100 text-xs mt-1 font-medium leading-relaxed">
            Set up your digital stall instantly. Take orders, receive WhatsApp inquiries, and get paid with MTN MoMo.
          </p>
        </div>
      </div>

      <div className="px-4 -mt-6 relative z-10 flex-1 max-w-md mx-auto w-full">
        {/* Stall Category Templates */}
        <div className="bg-white p-4 rounded-3xl shadow-sm border border-gray-100 mb-4">
          <div className="flex items-center gap-1.5 mb-2 px-0.5">
            <Sparkles size={14} className="text-emerald-600" />
            <span className="text-[11px] font-black text-gray-800 uppercase tracking-wider">
              Stall Category Templates
            </span>
          </div>
          <p className="text-[10px] text-gray-500 mb-3 leading-relaxed">
            Choose a template below to auto-complete category and description details instantly:
          </p>

          <div className="flex gap-2 overflow-x-auto no-scrollbar pb-1">
            {TradePresets.map((preset) => (
              <button
                key={preset.label}
                type="button"
                onClick={() => handleApplyPreset(preset)}
                className="flex items-center gap-2 px-3 py-2 bg-slate-50 hover:bg-emerald-50 hover:border-emerald-200 border border-slate-100 rounded-2xl active:scale-95 transition-all shrink-0"
              >
                <span className="text-lg">{preset.icon}</span>
                <div className="text-left">
                  <p className="text-[10px] font-black text-gray-800 leading-tight">{preset.label}</p>
                  <p className="text-[8px] text-gray-400 capitalize">{preset.subcategory}</p>
                </div>
              </button>
            ))}
          </div>
        </div>

        {/* Dynamic Trader Form */}
        <form onSubmit={handleSubmit} className="flex flex-col gap-4">
          {/* Shop Name */}
          <div className="bg-white p-4 rounded-3xl shadow-sm border border-slate-100 space-y-1.5">
            <label className="text-xs font-black text-gray-800 uppercase tracking-wider">Stall / Business Name</label>
            <div className="bg-slate-50 border border-slate-100 focus-within:border-emerald-500 rounded-2xl flex items-center px-3.5 py-3 transition-all">
              <Store size={18} className="text-gray-400 mr-2.5 shrink-0" />
              <input 
                type="text" 
                value={shopName}
                onChange={e => setShopName(e.target.value)}
                placeholder="e.g. Sipho's Fresh Cabbages" 
                required 
                className="bg-transparent flex-1 outline-none text-xs font-semibold text-gray-800 placeholder-gray-400" 
              />
            </div>
          </div>

          {/* Location Details */}
          <div className="bg-white p-4 rounded-3xl shadow-sm border border-slate-100 space-y-1.5">
            <label className="text-xs font-black text-gray-800 uppercase tracking-wider">Market Location / Stall Number</label>
            <div className="bg-slate-50 border border-slate-100 focus-within:border-emerald-500 rounded-2xl flex items-center px-3.5 py-3 transition-all">
              <MapPin size={18} className="text-gray-400 mr-2.5 shrink-0" />
              <input 
                type="text" 
                value={location}
                onChange={e => setLocation(e.target.value)}
                placeholder="e.g. Mbabane Market Stall 4" 
                required
                className="bg-transparent flex-1 outline-none text-xs font-semibold text-gray-800 placeholder-gray-400" 
              />
            </div>
          </div>

          {/* WhatsApp Contact */}
          <div className="bg-white p-4 rounded-3xl shadow-sm border border-slate-100 space-y-1.5">
            <div className="flex justify-between items-center">
              <label className="text-xs font-black text-gray-800 uppercase tracking-wider">WhatsApp Phone Number</label>
              <span className="text-[9px] text-emerald-600 font-bold">For Customer Inquiries</span>
            </div>
            <div className="bg-slate-50 border border-slate-100 focus-within:border-emerald-500 rounded-2xl flex items-center px-3.5 py-3 transition-all">
              <MessageCircle size={18} className="text-emerald-600 mr-2.5 shrink-0" />
              <input 
                type="tel" 
                value={whatsapp}
                onChange={e => setWhatsapp(e.target.value)}
                placeholder="+268 7611 2233" 
                required
                className="bg-transparent flex-1 outline-none text-xs font-mono font-semibold text-gray-800 placeholder-gray-400" 
              />
            </div>
          </div>

          {/* Description with auto-generator */}
          <div className="bg-white p-4 rounded-3xl shadow-sm border border-slate-100 space-y-2">
            <div className="flex justify-between items-center">
              <label className="text-xs font-black text-gray-800 uppercase tracking-wider">About Your Goods</label>
              <button
                type="button"
                onClick={handleAutoGenerateDesc}
                className="text-[10px] text-emerald-700 font-bold bg-emerald-50 px-2.5 py-1 rounded-xl flex items-center gap-1 hover:bg-emerald-100 transition-colors"
              >
                <Sparkles size={11} />
                <span>Auto-write</span>
              </button>
            </div>
            <textarea
              rows={3}
              value={desc}
              onChange={e => setDesc(e.target.value)}
              placeholder="Tell buyers what you sell, fresh harvests, or custom services..."
              className="w-full text-xs p-3 rounded-2xl border border-gray-200 focus:outline-none focus:ring-2 focus:ring-emerald-500 bg-gray-50/50"
            />
          </div>

          {/* Submit Button */}
          <button
            type="submit"
            disabled={isSubmitting}
            className="w-full bg-emerald-600 hover:bg-emerald-700 disabled:opacity-50 text-white font-extrabold text-sm p-4 rounded-2xl shadow-lg transition-all flex items-center justify-center gap-2 active:scale-95 mt-2"
          >
            {isSubmitting ? (
              <>
                <Loader2 size={18} className="animate-spin" />
                <span>Opening Your Stall...</span>
              </>
            ) : (
              <>
                <span>Publish Digital Stall</span>
                <ArrowRight size={18} />
              </>
            )}
          </button>
        </form>
      </div>
    </div>
  );
}
