import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { 
  Store, 
  Camera, 
  MessageCircle, 
  MapPin, 
  ArrowRight, 
  Sparkles, 
  CheckCircle2, 
  Leaf, 
  Pizza, 
  Shirt, 
  Wrench, 
  Scissors, 
  Smartphone, 
  Hammer, 
  Home as HomeIcon,
  HelpCircle,
  Clock
} from 'lucide-react';
import { CATEGORIES, Seller } from '../data/mockData';
import { db } from '../lib/firebase';
import { doc, setDoc } from 'firebase/firestore';

// Dynamic helper icons for quick trade selectors
const TradePresets = [
  { label: 'Veggie Vendor', icon: '🥬', category: 'agri', subcategory: 'Vegetables', desc: 'Fresh local farm vegetables sorted daily.' },
  { label: 'Fruit Seller', icon: '🍎', category: 'agri', subcategory: 'Fruits', desc: 'Ripe, delicious tropical and citrus fruits.' },
  { label: 'Street Food Stall', icon: '🍲', category: 'food', subcategory: 'Street food', desc: 'Warm, savory home-made local meals & snacks.' },
  { label: 'Tailor/Fashion', icon: '🧵', category: 'clothing', subcategory: 'Tailoring', desc: 'Custom traditional fits and professional stitching.' },
  { label: 'Hair Salon', icon: '💇', category: 'beauty', subcategory: 'Hair salons', desc: 'Modern styles, cuts, and braiding.' },
  { label: 'Mechanic Workshops', icon: '🔧', category: 'automotive', subcategory: 'Mechanics', desc: 'Reliable car diagnostics, repairs, and tuning.' },
  { label: 'Plumbing Service', icon: '🚰', category: 'construction', subcategory: 'Plumbers', desc: 'Expert leak repairs, installations, and piping.' },
  { label: 'Phone Repairs', icon: '📱', category: 'electronics', subcategory: 'Phones', desc: 'Screen repairs, battery replacement, and diagnostics.' }
];

export default function RegisterSeller() {
  const navigate = useNavigate();

  // Onboarding Form States
  const [shopName, setShopName] = useState('');
  const [category, setCategory] = useState('agri');
  const [subcategory, setSubcategory] = useState('Vegetables');
  const [whatsapp, setWhatsapp] = useState('');
  const [location, setLocation] = useState('');
  const [desc, setDesc] = useState('');
  const [logoPreset, setLogoPreset] = useState('🟢');
  const [isGenerating, setIsGenerating] = useState(false);

  // Apply a template immediately
  const handleApplyPreset = (preset: typeof TradePresets[0]) => {
    setCategory(preset.category);
    setSubcategory(preset.subcategory);
    setDesc(preset.desc);
    setLogoPreset(preset.icon);
    if (!shopName) {
      setShopName(`My ${preset.label} Shop`);
    }
  };

  // Auto-generate description to remove copywriting barriers
  const handleAutoGenerateDesc = () => {
    setIsGenerating(true);
    setTimeout(() => {
      const selectedCatObj = CATEGORIES.find(c => c.id === category);
      const categoryLabel = selectedCatObj ? selectedCatObj.name : 'Local Goods';
      const possibleName = shopName || 'Our humble store';
      
      const generatorTemplates = [
        `Welcome to ${possibleName}! We are proud local traders specializing in high-quality ${subcategory} and family-friendly products in Eswatini. Tap on the WhatsApp button to chat directly, check our inventory, and get same-day delivery right to your doorstep. Supporting community development starts here!`,
        `Quality and reliability are our top priorities at ${possibleName}. Offering premium ${subcategory} under the ${categoryLabel} category. Zero-delay local orders, fast MoMo pricing, and trusted Eswatini distribution. Reach out directly on WhatsApp with any product requests!`,
        `Your neighborhood home for ${subcategory}. At ${possibleName}, we provide friendly service, affordable rates, and high-rate local sourcing. Chat with us on MoMo/WhatsApp to place custom delivery requests now!`
      ];
      
      const randomIdx = Math.floor(Math.random() * generatorTemplates.length);
      setDesc(generatorTemplates[randomIdx]);
      setIsGenerating(false);
    }, 850);
  };

  return (
    <div className="bg-slate-50 min-h-screen pb-24 w-full flex flex-col font-sans">
      {/* Visual Hub Banner representing Core Vision */}
      <div className="bg-gradient-to-br from-green-700 via-green-600 to-emerald-800 px-6 pt-10 pb-12 rounded-b-[40px] text-white shadow-lg relative overflow-hidden">
        <div className="absolute top-0 right-0 w-32 h-32 bg-white/5 rounded-full blur-2xl pointer-events-none"></div>
        <div className="absolute -bottom-10 -left-6 w-24 h-24 bg-emerald-500/20 rounded-full blur-xl pointer-events-none"></div>
        
        <div className="max-w-md mx-auto">
          <span className="text-[10px] bg-emerald-500/30 text-emerald-100 font-extrabold px-3 py-1 rounded-full uppercase tracking-wider border border-white/10">
            ⏰ 2-Minute Setup
          </span>
          <h1 className="text-3xl font-black mt-3 font-display tracking-tight text-white leading-tight">
            Become a Digital Merchant
          </h1>
          <p className="text-emerald-100 text-xs mt-2 font-medium leading-relaxed max-w-[320px]">
             Set up your digital home instantly. No websites, no graphic design, and no complex settings. Just your phone, WhatsApp, and your custom trades.
          </p>
        </div>
      </div>

      <div className="px-4 -mt-6 relative z-10 flex-1 max-w-md mx-auto w-full">
        {/* Quick Trade Setup Sliders */}
        <div className="bg-white p-4 rounded-3xl shadow-md border border-gray-100 mb-6">
          <div className="flex items-center gap-1.5 mb-2.5 px-0.5">
            <Sparkles size={14} className="text-yellow-600 animate-pulse" />
            <span className="text-[11px] font-black text-gray-800 uppercase tracking-wider">
              Quick Setup Templates
            </span>
          </div>
          <p className="text-[10px] text-gray-500 mb-3 leading-relaxed">
            Are you one of these local traders? Tap anyone to instantly copy full category setups & description starters!
          </p>

          <div className="flex gap-2.5 overflow-x-auto no-scrollbar pb-1">
            {TradePresets.map((preset) => (
              <button
                key={preset.label}
                type="button"
                onClick={() => handleApplyPreset(preset)}
                className="flex items-center gap-2 px-3 py-2 bg-slate-50 hover:bg-slate-100 border border-slate-100 rounded-2xl active:scale-95 transition-transform shrink-0"
              >
                <span className="text-lg">{preset.icon}</span>
                <div className="text-left">
                  <p className="text-[10px] font-black text-gray-800 leading-tight">{preset.label}</p>
                  <p className="text-[8px] text-gray-400 capitalize">{preset.subcategory}</p>
                </div>
              </button>
            ))}
          </div>
        </div>

        {/* Real-Time Live Shop Preview */}
        <div className="bg-gradient-to-br from-slate-900 to-indigo-950 text-white rounded-3xl p-5 shadow-lg relative overflow-hidden mb-6 border border-slate-800/80">
          <div className="absolute top-0 right-0 bg-yellow-500 text-slate-950 text-[8px] font-bold px-2 py-0.5 rounded-bl-xl uppercase tracking-widest flex items-center gap-0.5">
            <Sparkles size={8} /> LIVE PREVIEW
          </div>
          <div className="flex gap-3.5 items-start">
            <div className="w-12 h-12 bg-white/10 rounded-2xl border border-white/20 flex items-center justify-center text-xl shrink-0">
              {logoPreset}
            </div>
            <div className="flex-1 min-w-0">
              <h3 className="font-extrabold text-sm text-white truncate">
                {shopName || 'Sipho\'s Veggies & Sprays'}
              </h3>
              <p className="text-[9px] text-slate-300 mt-0.5 flex items-center gap-1">
                <MapPin size={9} className="text-emerald-400" />
                <span className="truncate">{location || 'Manzini Market, Stall 4'}</span>
              </p>
              
              <div className="flex flex-wrap gap-1.5 mt-2">
                <span className="text-[8px] bg-green-500/20 text-green-300 px-2 py-0.5 rounded-md font-bold tracking-wide uppercase border border-green-500/20">
                  {category}
                </span>
                <span className="text-[8px] bg-indigo-500/20 text-indigo-300 px-2 py-0.5 rounded-md font-bold tracking-wide uppercase border border-indigo-500/20">
                  {subcategory}
                </span>
              </div>
            </div>
          </div>
          
          <div className="mt-4 bg-white/5 border border-white/10 rounded-2xl p-2.5 text-[9px] text-slate-300">
            <p className="font-bold text-white mb-1 tracking-wide flex items-center gap-1 text-[8px] uppercase text-emerald-400">
              <MessageCircle size={10} /> WhatsApp Auto-Hook
            </p>
            <p className="line-clamp-2 leading-relaxed">
              {desc || 'Type some details below, or hit "Auto-write Description" to write a wonderful intro description instantly!'}
            </p>
            <p className="mt-1.5 font-mono text-emerald-400 font-bold flex items-center gap-1 text-[8px]">
              📱 Direct Chat Line: +268 {whatsapp || '7123 4567'}
            </p>
          </div>
        </div>

        {/* Dynamic Trader Form */}
        <form className="flex flex-col gap-5 mt-4" onSubmit={async (e) => { 
          e.preventDefault(); 
          const newSellerId = `custom-seller-${Date.now()}`;
          const newSellerObj: Seller = {
            id: newSellerId,
            name: shopName,
            location: location || 'Mbabane Marketplace, Stall 4',
            hours: '08:00 - 17:30',
            phone: whatsapp ? `+268 ${whatsapp}` : '+268 7600 0000',
            rating: 5.0,
            reviews: 0,
            deliveryAvailable: true,
            paymentMethods: ['MTN MoMo', 'Cash'],
            bannerUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&q=80&w=800',
            logoUrl: 'https://images.unsplash.com/photo-1596422846543-74c6fc0e2811?auto=format&fit=crop&q=80&w=200',
            description: desc || 'Premium quality local goods.',
            verificationLevel: 'basic',
            category: CATEGORIES.find(c => c.id === category)?.name || 'Agriculture'
          };
          try {
            await setDoc(doc(db, 'sellers', newSellerId), newSellerObj);
            localStorage.setItem('emakethe_active_seller_id', newSellerId);
            navigate('/dashboard'); 
          } catch (err) {
            console.error(err);
            alert("Error registering merchant. Please try again.");
          }
        }}>
          
          {/* Shop Name */}
          <div className="flex flex-col gap-1.5 bg-white p-4 rounded-3xl shadow-sm border border-slate-100">
            <div className="flex justify-between items-center">
              <label className="text-xs font-black text-gray-800 uppercase tracking-wider">Shop Name</label>
              <span className="text-[9px] text-gray-400 font-medium">Clear & Simple</span>
            </div>
            <div className="bg-slate-50 border border-slate-100 focus-within:border-green-500 focus-within:ring-2 focus-within:ring-green-100 rounded-2xl flex items-center px-4 py-3.5 transition-all">
              <Store size={18} className="text-gray-400 mr-2.5" />
              <input 
                type="text" 
                value={shopName}
                onChange={e => setShopName(e.target.value)}
                placeholder="e.g. Sipho's Organic Crops" 
                required 
                className="bg-transparent flex-1 outline-none text-xs font-semibold text-gray-800 placeholder-gray-400" 
              />
            </div>
          </div>

          {/* Location Details */}
          <div className="flex flex-col gap-1.5 bg-white p-4 rounded-3xl shadow-sm border border-slate-100">
            <div className="flex justify-between items-center">
              <label className="text-xs font-black text-gray-800 uppercase tracking-wider">Where are you based?</label>
              <span className="text-[9px] text-gray-400 font-medium">Stall or City</span>
            </div>
            <div className="bg-slate-50 border border-slate-100 focus-within:border-green-500 focus-within:ring-2 focus-within:ring-green-100 rounded-2xl flex items-center px-4 py-3.5 transition-all">
              <MapPin size={18} className="text-gray-400 mr-2.5" />
              <input 
                type="text" 
                value={location}
                onChange={e => setLocation(e.target.value)}
                placeholder="e.g. Mbabane Terminal Square, Stall A7" 
                required
                className="bg-transparent flex-1 outline-none text-xs font-semibold text-gray-800 placeholder-gray-400" 
              />
            </div>
          </div>

          {/* WhatsApp Direct MoMo Number */}
          <div className="flex flex-col gap-1.5 bg-white p-4 rounded-3xl shadow-sm border border-slate-100">
            <div className="flex justify-between items-center">
              <label className="text-xs font-black text-gray-800 uppercase tracking-wider">WhatsApp Number</label>
              <span className="text-[9px] text-emerald-600 font-bold bg-emerald-50 px-2 py-0.5 rounded-full">MoMo Live</span>
            </div>
            <div className="bg-slate-50 border border-slate-100 focus-within:border-green-500 focus-within:ring-2 focus-within:ring-green-100 rounded-2xl flex items-center px-4 py-3.5 transition-all">
              <MessageCircle size={18} className="text-gray-400 mr-2.5" />
              <span className="text-gray-600 mr-1.5 text-xs font-bold leading-none">+268</span>
              <input 
                type="tel" 
                value={whatsapp}
                onChange={e => setWhatsapp(e.target.value)}
                placeholder="7123 4567" 
                pattern="[7][68912]\d{6}"
                title="Please enter an 8-digit Eswatini cellular number starting with 7 (e.g. 76123456, 78123456, 71234567)."
                required 
                className="bg-transparent flex-1 outline-none text-xs font-bold text-gray-800 placeholder-gray-400 font-mono tracking-widest" 
              />
            </div>
            <p className="text-[10px] text-slate-400 leading-normal mt-0.5">
              Used directly by buyers to place cash-on-delivery or MoMo payment orders in one click.
            </p>
          </div>

          {/* Trade Category Matrix info */}
          <div className="bg-white p-4 rounded-3xl shadow-sm border border-slate-100 flex flex-col gap-4">
            <label className="text-xs font-black text-gray-800 uppercase tracking-wider -mb-1 block">Trade Category</label>
            
            <div className="grid grid-cols-2 gap-3">
              <div className="flex flex-col gap-1">
                <span className="text-[9px] text-gray-400 font-bold">CORE FIELD</span>
                <select 
                  value={category} 
                  onChange={e => {
                    const catId = e.target.value;
                    setCategory(catId);
                    const categoryObj = CATEGORIES.find(c => c.id === catId);
                    if (categoryObj && categoryObj.subcategories.length > 0) {
                      setSubcategory(categoryObj.subcategories[0]);
                    }
                  }}
                  className="w-full bg-slate-50 border border-slate-100 rounded-xl p-3 text-xs focus:border-green-500 focus:bg-white outlook-none font-bold text-gray-700 select-style"
                >
                  {CATEGORIES.map(c => (
                    <option key={c.id} value={c.id}>{c.name}</option>
                  ))}
                </select>
              </div>

              <div className="flex flex-col gap-1">
                <span className="text-[9px] text-gray-400 font-bold">STREET TRADE / SPECIALTY</span>
                <select 
                  value={subcategory} 
                  onChange={e => setSubcategory(e.target.value)}
                  className="w-full bg-slate-50 border border-slate-100 rounded-xl p-3 text-xs focus:border-green-500 focus:bg-white outlook-none font-bold text-gray-700 select-style"
                >
                  {(CATEGORIES.find(c => c.id === category)?.subcategories || []).map(sub => (
                    <option key={sub} value={sub}>{sub}</option>
                  ))}
                </select>
              </div>
            </div>
          </div>

          {/* Interactive Description Auto-Writer */}
          <div className="flex flex-col gap-1.5 bg-white p-4 rounded-3xl shadow-sm border border-slate-100">
            <div className="flex justify-between items-center mb-1">
              <label className="text-xs font-black text-gray-800 uppercase tracking-wider">Store Description</label>
              <button 
                type="button" 
                onClick={handleAutoGenerateDesc}
                disabled={isGenerating}
                className="text-[10px] bg-purple-50 text-purple-700 font-bold px-2 py-1 rounded-lg flex items-center gap-1 active:scale-95 transition-all self-end hover:bg-purple-100 disabled:opacity-50"
              >
                <Sparkles size={11} className={isGenerating ? 'animate-spin' : ''} />
                {isGenerating ? 'Drafting...' : 'Auto-write Intro'}
              </button>
            </div>
            
            <textarea 
              value={desc}
              onChange={e => setDesc(e.target.value)}
              placeholder="Tell shoppers what specialties or services you render. Click 'Auto-write' above to save time!" 
              rows={4} 
              required
              className="w-full border border-slate-100 bg-slate-50 rounded-2xl p-3.5 text-xs text-slate-700 focus:border-green-500 focus:bg-white focus:ring-2 focus:ring-green-500/20 outline-none resize-none transition-all font-medium leading-relaxed"
            ></textarea>
          </div>

          {/* Form Action */}
          <button 
            type="submit" 
            className="mt-3 bg-gradient-to-r from-green-600 to-emerald-600 hover:from-green-700 hover:to-emerald-700 text-white py-4 px-6 rounded-full font-bold shadow-lg shadow-green-600/20 active:scale-95 transition-all text-sm flex items-center justify-center gap-2 group border border-green-500/10"
          >
            Launch Shop Online <ArrowRight size={16} className="group-hover:translate-x-1 transition-transform" />
          </button>
        </form>

        {/* Core Vision Values Checklist */}
        <div className="mt-8 bg-white/40 rounded-3xl p-5 border border-slate-200/50 flex flex-col gap-3">
          <h4 className="text-[10px] uppercase font-black text-slate-500 tracking-wider">Under The Hood Benefits</h4>
          <div className="flex items-start gap-2.5">
            <CheckCircle2 size={15} className="text-green-600 mt-0.5 shrink-0" />
            <p className="text-[10px] text-slate-600 leading-normal font-medium"><strong>No Maintenance Fees</strong>: This platform serves as your persistent public catalog. Absolutely free of digital tax or monthly domains.</p>
          </div>
          <div className="flex items-start gap-2.5">
            <CheckCircle2 size={15} className="text-green-600 mt-0.5 shrink-0" />
            <p className="text-[10px] text-slate-600 leading-normal font-medium"><strong>Zero Logistics Setup</strong>: All incoming products auto-match with local verified driver-couriers across town.</p>
          </div>
          <div className="flex items-start gap-2.5">
            <CheckCircle2 size={15} className="text-green-600 mt-0.5 shrink-0" />
            <p className="text-[10px] text-slate-600 leading-normal font-medium"><strong>Unified Wallet System</strong>: Receive instantaneous buyer purchases directly into your secure wallet. Withdraw to standard Momo accounts cleanly.</p>
          </div>
        </div>
      </div>
    </div>
  );
}
